###

GET http://localhost:9000/api/employees

###

POST http://localhost:9000/api/employees
Content-Type: application/json

{
    "name":"elvis",
    "position": "trainee dev.",
    "office": "seven floor",
    "salary": "26000"
    
}